# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy a new Mono Weather version to the Google Play"
  lane :deployMono do
    gradle(
        task: "clean bundle",
        flavor: "MonoWeather",
        build_type: "Release",
        )
    upload_to_play_store(
        aab: "app/build/outputs/bundle/monoWeather/app-driver-release.aab",
        json_key: "google-play-key.json",
        package_name: "h_mal.appttude.com.monoWeather")
  end

  desc "Deploy a new Atlas Weather version to the Google Play"
  lane :deployMono do
    gradle(
        task: "clean bundle",
        flavor: "AtlasWeather",
        build_type: "Release",
        )
    upload_to_play_store(
        aab: "app/build/outputs/bundle/atlasWeather/app-driver-release.aab",
        json_key: "google-play-key.json",
        package_name: "h_mal.appttude.com.monoWeather")
  end
end